<<<<<<< HEAD
openapi: '3.0.0'
info:
  title: Sample API
  description: API description in Markdown.
=======
openapi: "3.0.0"
info:
  title: 5팀 모코코 API 명세서
  description: |
    # 주의사항
    backend 폴더 README.md 파일에 대략적인 사용 방법이 있으니 참고하세요.
    yaml파일의 구체적인 작성 요령은
    - https://swagger.io/docs/specification/about/
    - https://swagger.io/specification/
    - users MVP에 대한 yaml 파일들
    을 참고하세요.

>>>>>>> 768c4f7e7c7ca3fadc70c29177723144b73b345f
  version: 1.0.0

servers:
  - url: localhost:5001/docs

<<<<<<< HEAD
paths:
  /users/signup:
    $ref: './user/users-signup.yaml'
  /users/signin:
    $ref: './user/users-signin.yaml'
=======
tags:
  - name: users
    description: 유저 로그인, 회원가입, 탈퇴, 정보 조회, 정보 수정 등

paths:
  /users/signup:
    $ref: "./user/users-signup.yaml"
  /users/signin:
    $ref: "./user/users-signin.yaml"
  /users:
    $ref: "./user/users.yaml"
  /users/{userId}:
    $ref: "./user/users-userId.yaml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
>>>>>>> 768c4f7e7c7ca3fadc70c29177723144b73b345f
